### ISSUE TITLE
Click Done ✅ and get "Your Playlist Is Empty"

### ISSUE THREAD

**Issue by janabouc** [sethgecko13/MeeZeeFit#15]
I tried this a few times--made a screen recording of my confusion trying to Add to playlist, find  where that addition went (couldn't) and then click Done to see what happens. I tried 3 times and always got this "Your Playlist Is Empty" card. ![image](https://github.com/sethgecko13/MeeZeeFit/assets/60453297/f33b8ec9-200e-47c9-b37e-ba62a6c23a6a)

I don't know if GitHub will display the photo from phone. If you want the screen recording let me know and I'll upload from computer. I think GitHub doesn't like videos/ photos added from phone.

**Comment by sethgecko13** [comment]
Thanks! I wasn't able to replicate this, so... yeah! If you could upload the video that would be awesome! (Or I can give you my email to email to if that would be easier).

**Comment by janabouc** [comment]
The video was way too long because it had minutes of me trying to save a class from my imported YouTube playlist to a playlist and then looking for where the class had saved and not finding it.

So I cut out all that and saved the clip and uploaded it to YouTube. I'm just waiting for YouTube to process it and I'll send you the link (the video was too big for GitHub or email).

**Comment by sethgecko13** [comment]
awesome. thank you!!!! I also just an updated TestFlight version that lets you choose how to import the playlist.

**Comment by janabouc** [comment]
https://youtu.be/eojWG4SJyEw
Here's the video showing it happen 2 times

**Comment by janabouc** [comment]
> awesome. thank you!!!! I also just an updated TestFlight version that lets you choose how to import the playlist.

So in YouTube I think the only things you can do with a playlist is save to it and play from it but not rearrange the list or mark them as done. In a Meezee playlist can you rearrange and mark as done or move or save to a different playlist? 

Can you actually save to a playlist from a playlist? Maybe the odd result and crashes was me trying to do something that isn't an option?

**Comment by sethgecko13** [comment]
In my YouTube app I can drag and drop my own playlists but not other peoples playlists.

In meezee you can drag and drop your own meezee playlists, or you can import a YouTube playlist that someone else made and rearrange it. Which I don’t think you can easily do in YouTube.

in meezee if you mark as done it shows a green check mark regardless of whether it’s a meezee playlist or a YouTube playlist.  But you mark done from within the workout viewing screen not from the playlist edit screen.

in meezee you can copy to a new playlist by selecting add to playlist.

You can’t save from one playlist to another directly in meezee.  That’s something that YouTube does let you do.  I’ve been toying with how to add that, but.. it’s all about tradeoffs.  I really dislike YouTube’s current paradigm of 2 steps to add a video. First step is to say add to playlist and second is to choose the playlist.  When I’m just building a playlist it annoys me to have 2 steps for every video instead of “just add it to the current playlist I’m making” which is how meezee handles it. Of course, I’m open to change if the current way I did it doesn’t work or doesn’t make sense.

I don’t think the crash was on you. It was almost certainly on me and I thank you for catching it.  I just need to find what’s causing it now.

whew… I *think* that covers everything.

**Comment by sethgecko13** [comment]
> https://youtu.be/eojWG4SJyEw Here's the video showing it happen 2 times

Thanks for sharing. Unfortunately, the video seemed truncated and I couldn’t see the top of bottom of screen so I couldn’t quite tell what you were clicking at what point.

i *think* if you want to email it to mz at meezeeco.com and send as an iCloud link instead of sending the whole file.. that should make it fairly painless to share.

**Comment by sethgecko13** [comment]
Thanks for the video. This is a pretty big bug that I feel embarrassed about, but I never would have gotten it if you hadn't had a video of it. Because I was just testing it the way *I* do playlists. Doh.  

I have a fix on my phone but I want to test it a bit before pushing it up. Will probably push it up tomorrow if all goes well.

**Comment by janabouc** [comment]
Glad I could help. By the time I'm ready to use it on the regular it will be so nicely tuned up.

**Comment by sethgecko13** [comment]
Fixed in build 2023.10.01 (418)
