### ISSUE TITLE
UI questions and suggestions

### ISSUE THREAD

**Issue by janabouc** [sethgecko13/MeeZeeFit#6]
I've tried to get started with the beta and have a few notes. 

1. I wanted to add a few classes to a workout list in MZ (sorry for abbreviating) that I've been saving in my email. I did a search/youtube: Saran Posture and the right class was the first one displayed. 👍🏻!

2. I clicked on that class and saw the options shopping cart, heart, nope, did it. I wasn't sure of the meaning of those and wanted to go back. It took a minute to find the back arrow top left because it looks like it's connected to the word Nope. 

Suggestions: add hovering explainer text for each icon or an i icon to get the explanation of their useage. Separate back arrow from nope by color or space. 

3. I went back to the found list and clicked on the shopping cart but on the wrong class. Shopping cart turned green. I clicked again to toggle it off because wrong class but it stayed green. No way to unselect?

4. Clicking the class listing to go to the page for a class to add a class to my playlist (which i guess you call Routines). 

(I suggest calling it Playlist--don't understand Routines). 
I clicked the shopping cart and it didn't change color. So i clicked again. I ended up adding the class multiple times because it was actually working but not changing color. 

5. The app options Workouts and Classes are confusing as they mean the same thing to me. But when i click on Classes it takes me to a page to schedule workouts for the week. 
I suggest changing that option to Schedule with a calendar icon. Also no option there yet for reformer Pilates. 

6. Not sure of the correct meanings/purpose of the 4 choices on a class page: Nope, Did It, ❤️, 🛒.  My guess is:

Nope = either a)did it and didn't like it so don't show it again or b) haven't done it yet or c) don't wanna do this one? (I like the last one-sometimes i scrub through a class and decide it's not for me and would love to mark it as don't do it) 

Did it = mark it as done? (this would be helpful since YouTube doesn't indicate this)

🛒= add to my playlist aka Routine

❤️ not sure what this does on this page. I think on a channel search it adds the channel to your favorite channels. But what does it do here?

7. Using a 🛒 with a plus to mean add to my list is a little confusing. 

I suggest instead just using a ➕ that turns to a ✅ when saved. Shopping cart usually indicates purchase so i was afraid i would be charged if i clicked it. 

Ok there's more to explore but I'm out of time. I hope this helps and look forward to understanding the app better and using it daily!!

**Comment by sethgecko13** [comment]
> I've tried to get started with the beta and have a few notes.
> 
> 1. I wanted to add a few classes to a workout list in MZ (sorry for abbreviating) that I've been saving in my email. I did a search/youtube: Saran Posture and the right class was the first one displayed. 👍🏻!

Yay!

> 2. I clicked on that class and saw the options shopping cart, heart, nope, did it. I wasn't sure of the meaning of those and wanted to go back. It took a minute to find the back arrow top left because it looks like it's connected to the word Nope.
> 

I'll remove "Nope" and just make it an obvious back button. I need to think about the rest of them.  The "Did It" is to log the workout as complete.  The heart is to save as a favorite video. The cart is to add it to the cart.  Good feedback that they weren't clear.  Thanks!

> Suggestions: add hovering explainer text for each icon or an i icon to get the explanation of their useage. Separate back arrow from nope by color or space.
> 
> 3. I went back to the found list and clicked on the shopping cart but on the wrong class. Shopping cart turned green. I clicked again to toggle it off because wrong class but it stayed green. No way to unselect?

Good feedback. Will fix.  If you click "Routines" down at the bottom that brings up the shopping cart and you can swipe left to remove items from the cart there. But it would be logical that clicking the green cart button would deselect. I'll fix that.

> 4. Clicking the class listing to go to the page for a class to add a class to my playlist (which i guess you call Routines).
> 
> (I suggest calling it Playlist--don't understand Routines). I clicked the shopping cart and it didn't change color. So i clicked again. I ended up adding the class multiple times because it was actually working but not changing color.

I need to digest this. Good feedback and probably a bug.  The reason I called it routine instead of playlist is mainly because playlists are already a thing on YouTube.  Maybe I should just call it a playlist, but... it gets complicated because you can edit routines in the app, but you can't edit YouTube playlists.  Why can't you edit playlists? Well... I wanted to avoid the extra step of having to log into YouTube to edit your own playlists, and I want to preserve the privacy aspects of the app (it actually makes it mildly difficult for YouTube to track what you're watching for advertising purposes).

> 
> 5. The app options Workouts and Classes are confusing as they mean the same thing to me. But when i click on Classes it takes me to a page to schedule workouts for the week. 

Good feedback.  Do you know what version of beta you're using?  On my latest version I've renamed it "Workouts" and "Schedule".  Is that any better?

>    I suggest changing that option to Schedule with a calendar icon. Also no option there yet for reformer Pilates.
> 6. Not sure of the correct meanings/purpose of the 4 choices on a class page: Nope, Did It, ❤️, 🛒.  My guess is:
> 
> Nope = either a)did it and didn't like it so don't show it again or b) haven't done it yet or c) don't wanna do this one? (I like the last one-sometimes i scrub through a class and decide it's not for me and would love to mark it as don't do it)

yeah, it meant "Not gonna do it". But obviously not clear.  It doesn't prevent it from showing up again.

> 
> Did it = mark it as done? (this would be helpful since YouTube doesn't indicate this)

Yes.

> 
> 🛒= add to my playlist aka Routine

Yes.
> 
> ❤️ not sure what this does on this page. I think on a channel search it adds the channel to your favorite channels. But what does it do here?
> 
> 7. Using a 🛒 with a plus to mean add to my list is a little confusing.
> 
> I suggest instead just using a ➕ that turns to a ✅ when saved. Shopping cart usually indicates purchase so i was afraid i would be charged if i clicked it.

Good feedback.

> 
> Ok there's more to explore but I'm out of time. I hope this helps and look forward to understanding the app better and using it daily!!

Thanks so much!! this is awesome feedback.

**Comment by sethgecko13** [comment]
Ok, I coded up fixed for most of this. Will do a little internal testing and then push out a new beta tomorrow. I’ll drop a note with the build version here.

**Comment by janabouc** [comment]
A thought about playlist vs routine— peloton calls it a stack. You can
stack multiple classes and they use a + inside a square on a square.

**Comment by sethgecko13** [comment]
TestFlight version 2023.9.2 (build 371) released to address these issues.
